In [243]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn import utils
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

Import the Dataset

In [244]:
dataset = pd.read_csv('all_features_by_state_test.csv')

See the length and top 5 rows

In [245]:
len(dataset)
print(dataset.head())

             Unnamed: 0  CensusTract State_x  HUNVFlag_x  LILATracts_1And10_x  \
0  1400000US02013000100   2013000100  Alaska           1                    1   
1  1400000US02016000100   2016000100  Alaska           0                    1   
2  1400000US02016000200   2016000200  Alaska           0                    0   
3  1400000US02020000101   2020000101  Alaska           0                    0   
4  1400000US02020000102   2020000102  Alaska           0                    0   

   LILATracts_halfAnd10_x  LILATracts_Vehicle_x  LATracts1_y  LATracts10_y  \
0                       1                     1            1             1   
1                       1                     1            1             1   
2                       0                     0            1             0   
3                       0                     0            1             0   
4                       0                     0            1             0   

   LATracts20_y  ...  B19131_003E_diff  B191

Drop the row that is "Unnamed"

In [246]:
clean_dataset = dataset.drop(columns = ['Unnamed: 0','State_x','NAME2010','NAME2015','entropy_diff'])

In [247]:
clean_dataset.shape

(64573, 129)

In [248]:
clean_dataset.head()

CensusTract  HUNVFlag_x  LILATracts_1And10_x  LILATracts_halfAnd10_x  \
0   2013000100           1                    1                       1   
1   2016000100           0                    1                       1   
2   2016000200           0                    0                       0   
3   2020000101           0                    0                       0   
4   2020000102           0                    0                       0   

   LILATracts_Vehicle_x  LATracts1_y  LATracts10_y  LATracts20_y  \
0                     1            1             1             1   
1                     1            1             1             1   
2                     0            1             0             0   
3                     0            1             0             0   
4                     0            1             0             0   

   LATracts_half_y  LATracts1_x  ...  B19131_002E_diff  B19131_003E_diff  \
0                1            0  ...               159                72   
1                1            0  ...                34                22   
2                1            0  ...               246               152   
3                1            1  ...              -107               -13   
4                1            0  ...               194                57   

   B19126_001E_diff  B03002_009E_diff  B03002_010E_diff  B03002_011E_diff  \
0            2663.0               -46                 0               -46   
1           -1354.0               -35                 0               -35   
2            4327.0               117                 0               117   
3               NaN               359                 0               359   
4            9355.0               117                 0               117   

   entropy_index10_y  entropy_index15_x  HUNVFlag_y  HUNVFlag_diff  
0           1.436035           1.648337           1              0  
1           1.629681           1.430492           0              0  
2           1.476288           1.636992           0              0  
3           0.584863           0.691189           0              0  
4           0.800645           0.782535           1             -1  

[5 rows x 129 columns]

Replace NA's with zeros

In [249]:
nona_clean_dataset = clean_dataset.fillna(0)

In [250]:
nona_clean_dataset.head()

CensusTract  HUNVFlag_x  LILATracts_1And10_x  LILATracts_halfAnd10_x  \
0   2013000100           1                    1                       1   
1   2016000100           0                    1                       1   
2   2016000200           0                    0                       0   
3   2020000101           0                    0                       0   
4   2020000102           0                    0                       0   

   LILATracts_Vehicle_x  LATracts1_y  LATracts10_y  LATracts20_y  \
0                     1            1             1             1   
1                     1            1             1             1   
2                     0            1             0             0   
3                     0            1             0             0   
4                     0            1             0             0   

   LATracts_half_y  LATracts1_x  ...  B19131_002E_diff  B19131_003E_diff  \
0                1            0  ...               159                72   
1                1            0  ...                34                22   
2                1            0  ...               246               152   
3                1            1  ...              -107               -13   
4                1            0  ...               194                57   

   B19126_001E_diff  B03002_009E_diff  B03002_010E_diff  B03002_011E_diff  \
0            2663.0               -46                 0               -46   
1           -1354.0               -35                 0               -35   
2            4327.0               117                 0               117   
3               0.0               359                 0               359   
4            9355.0               117                 0               117   

   entropy_index10_y  entropy_index15_x  HUNVFlag_y  HUNVFlag_diff  
0           1.436035           1.648337           1              0  
1           1.629681           1.430492           0              0  
2           1.476288           1.636992           0              0  
3           0.584863           0.691189           0              0  
4           0.800645           0.782535           1             -1  

[5 rows x 129 columns]

Split dataset into train and test data. I decided to use 20% of the test data to train my model

In [251]:
x = nona_clean_dataset.iloc[:, 0:127]
y = nona_clean_dataset.iloc[:, 128]
y=y.astype('int')
x_train,x_test,y_train,y_test = train_test_split(x, y, random_state = 1, test_size=0.2)

Then, feature scaling on the training data to normalize it before we input. Also, make sure both the test and train data are transformed.

In [252]:
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.transform(x_test)

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


Define the model: Create KNN Classifier

In [253]:
from sklearn.model_selection import cross_val_predict
classifier = KNeighborsClassifier(n_neighbors = 113,p=3, metric = 'euclidean')

Fit the model

In [254]:
# lab_enc = preprocessing.LabelEncoder()
# encoded = lab_enc.fit_transform(y_train)
# print(utils.multiclass.type_of_target(y_train.astype('int')))
# y_pred = cross_val_predict(classifier,x,y,cv = 5)

In [255]:
lab_enc = preprocessing.LabelEncoder()
training_scores_encoded = lab_enc.fit_transform(y_train)
print(y_train)
print(utils.multiclass.type_of_target(y_train))
print(utils.multiclass.type_of_target(y_train.astype('int')))
print(utils.multiclass.type_of_target(y_train))

50362    0
43332   -1
8309     0
59229    0
21318    0
        ..
32511    0
5192     1
12172    0
33003    0
62501    0
Name: HUNVFlag_diff, Length: 51658, dtype: int64
multiclass
multiclass
multiclass


The amount of Nearest Neightbors

In [256]:
import math
math.sqrt(len(y_test))

113.64418154925487

Build the model 

In [257]:
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=113, p=3,
           weights='uniform')

Predict the response for test dataset

In [258]:
y_pred = classifier.predict(x_test)

In [259]:
y_pred
len(y_pred)

12915

Evaluate the Model

In [260]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[  160   736     0]
 [    2 10960    16]
 [    0   784   257]]


Print F1-Score -  takes into account the false positives

In [263]:
# print(f1_score(y_test,y_pred))

Print the Accuracy Score

In [262]:
print(accuracy_score(y_test,y_pred))

0.88091366627952


This is a fair fit for the model at 88%. Now, let's plot the data to visualize it

In [267]:
import sklearn
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import scale

import sklearn.metrics as sm
from sklearn import datasets
from sklearn.metrics import confusion_matrix,classification_report
from sklearn import datasets, neighbors
from mlxtend.plotting import plot_decision_regions

Build the model

In [268]:
clustering = KMeans(n_clusters = 3, random_state = 3)
clustering.fit(x_train, y_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=3, tol=0.0001, verbose=0)

In [278]:
print(clustering.labels_)

[1 2 0 ... 1 0 0]


Plotting my model output

In [269]:
desert_df = pd.DataFrame(nona_clean_dataset)

In [270]:
nona_clean_dataset.columns.tolist()

['CensusTract',
 'HUNVFlag_x',
 'LILATracts_1And10_x',
 'LILATracts_halfAnd10_x',
 'LILATracts_Vehicle_x',
 'LATracts1_y',
 'LATracts10_y',
 'LATracts20_y',
 'LATracts_half_y',
 'LATracts1_x',
 'LATracts10_x',
 'LATracts20_x',
 'LATracts_half_x',
 'LILATracts_1And20_x',
 'Unnamed: 16',
 'LILATracts_1And10_y',
 'LILATracts_halfAnd10_y',
 'LILATracts_Vehicle_y',
 'LILATracts_1And20_y',
 'LILATracts_1And10_diff',
 'LILATracts_halfAnd10_diff',
 'LILATracts_Vehicle_diff',
 'LILATracts_1And20_diff',
 'LATracts1_diff',
 'LATracts10_diff',
 'LATracts20_diff',
 'LATracts_half_diff',
 'prop_white',
 'prop_black',
 'prop_asian',
 'prop_hisp',
 'prop_nhopi',
 'prop_aian',
 'prop_multir',
 'totalprop',
 'totalpop10',
 'prop_white10',
 'prop_black10',
 'prop_asian10',
 'prop_hisp10',
 'prop_nhopi10',
 'prop_aian10',
 'prop_multir10',
 'Unnamed: 0_x',
 'STATE2010',
 'B01001_001E2010',
 'B01001_002E2010',
 'B01001_026E2010',
 'B01002_001E2010',
 'B01003_001E2010',
 'B19037_001E2010',
 'B19001_001E2010

In [271]:
desert_df.columns = ['CensusTract',
 'HUNVFlag_x',
 'LILATracts_1And10_x',
 'LILATracts_halfAnd10_x',
 'LILATracts_Vehicle_x',
 'LATracts1_y',
 'LATracts10_y',
 'LATracts20_y',
 'LATracts_half_y',
 'LATracts1_x',
 'LATracts10_x',
 'LATracts20_x',
 'LATracts_half_x',
 'LILATracts_1And20_x',
 'Unnamed: 16',
 'LILATracts_1And10_y',
 'LILATracts_halfAnd10_y',
 'LILATracts_Vehicle_y',
 'LILATracts_1And20_y',
 'HUNVFlag_diff',
 'LILATracts_1And10_diff',
 'LILATracts_halfAnd10_diff',
 'LILATracts_Vehicle_diff',
 'LILATracts_1And20_diff',
 'LATracts1_diff',
 'LATracts10_diff',
 'LATracts20_diff',
 'LATracts_half_diff',
 'prop_white',
 'prop_black',
 'prop_asian',
 'prop_hisp',
 'prop_nhopi',
 'prop_aian',
 'prop_multir',
 'totalprop',
 'totalpop10',
 'prop_white10',
 'prop_black10',
 'prop_asian10',
 'prop_hisp10',
 'prop_nhopi10',
 'prop_aian10',
 'prop_multir10',
 'Unnamed: 0_x',
 'STATE2010',
 'B01001_001E2010',
 'B01001_002E2010',
 'B01001_026E2010',
 'B01002_001E2010',
 'B01003_001E2010',
 'B19037_001E2010',
 'B19001_001E2010',
 'B17023_001E2010',
 'B17020A_014E2010',
 'B08303_002E2010',
 'B08303_010E2010',
 'B08301_010E2010',
 'B08301_002E2010',
 'B08202_004E2010',
 'B08202_020E2010',
 'B08137_002E2010',
 'B19326_001E2010',
 'B19301_001E2010',
 'B19131_002E2010',
 'B19131_003E2010',
 'B19126_001E2010',
 'B03002_009E2010',
 'B03002_010E2010',
 'B03002_011E2010',
 'state2010',
 'county2010',
 'tract2010',
 'Unnamed: 0_y',
 'STATE2015',
 'B01001_001E2015',
 'B01001_002E2015',
 'B01001_026E2015',
 'B01002_001E2015',
 'B01003_001E2015',
 'B19037_001E2015',
 'B19001_001E2015',
 'B17023_001E2015',
 'B17020A_014E2015',
 'B08303_002E2015',
 'B08303_010E2015',
 'B08301_010E2015',
 'B08301_002E2015',
 'B08202_004E2015',
 'B08202_020E2015',
 'B08137_002E2015',
 'B19326_001E2015',
 'B19301_001E2015',
 'B19131_002E2015',
 'B19131_003E2015',
 'B19126_001E2015',
 'B03002_009E2015',
 'B03002_010E2015',
 'B03002_011E2015',
 'state2015',
 'county2015',
 'tract2015',
 'B01001_001E_diff',
 'B01001_002E_diff',
 'B01001_026E_diff',
 'B01002_001E_diff',
 'B01003_001E_diff',
 'B19037_001E_diff',
 'B19001_001E_diff',
 'B17023_001E_diff',
 'B17020A_014E_diff',
 'B08303_002E_diff',
 'B08303_010E_diff',
 'B08301_010E_diff',
 'B08301_002E_diff',
 'B08202_004E_diff',
 'B08202_020E_diff',
 'B08137_002E_diff',
 'B19326_001E_diff',
 'B19301_001E_diff',
 'B19131_002E_diff',
 'B19131_003E_diff',
 'B19126_001E_diff',
 'B03002_009E_diff',
 'B03002_010E_diff',
 'B03002_011E_diff',
 'entropy_index10_y',
 'entropy_index15_x',
 'HUNVFlag_y']
y.columns=["HUNVFlag_y"]


In [275]:
clustering

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=3, tol=0.0001, verbose=0)

In [300]:
color_theme = np.array(['darkgray','lightsalmon','powderblue'])
plt.subplot(1,2,1)
plt.scatter(x=desert_df.HUNVFlag_x, y =desert_df.HUNVFlag_y, c = color_theme [desert_df.HUNVFlag_y], s= 50)
plt.title("Food Desert or not")
plt.subplot(1,2,2)
plt.scatter(x= desert_df.HUNVFlag_x,y= desert_df.HUNVFlag_y, c = color_theme[clustering.labels_],s=50 )
plt.title("K-Means Function")
if c_none or co is not None:
            c_array = None
else:  # <- from the not shown instructions above, c_none is False
            try:
                c_array = np.asanyarray(c, dtype=float)
if c_array.shape in xy_shape:  # <- True for case *A* => everything will be fine
                    c = np.ma.ravel(c_array)
else:  # <- in case *B* c_array.shape == (), while xy_shape == ((1,), (1,))
                    # Wrong size; it must not be intended for mapping.
                    c_array = None
            except ValueError:
                # Failed to make a floating-point array; c must be color specs.
                c_array = None

if c_array is None:  # <- True in case *B*
            try:
                # must be acceptable as PathCollection facecolors
                colors = mcolors.to_rgba_array(c)  # <- BOOM!
            except ValueError:
                # c not acceptable as PathCollection facecolor
                msg = ("c of shape {0} not acceptable as a color sequence "
                       "for x with size {1}, y with size {2}")
                raise ValueError(msg.format(c.shape, x.size, y.size))
else:
            colors = None  # use cmap, norm after collection is created

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 18)

In [283]:
plot_decision_regions(y_test, y_pred, clf=neighbors.KNeighborsClassifier(n_neighbors=113), legend=2)

ValueError: X must be a NumPy array. Found <class 'pandas.core.series.Series'>

In [303]:
def knn_comparison(data, k):
    x = nona_clean_dataset[['HUNVFlag_x','HUNVFlag_y']].values
    y = nona_clean_dataset['HUNVFlag_y'].astype(int).values
    clf = neighbors.KNeighborsClassifier(n_neighbors=k)
    clf.fit(x, y)
   # Plotting decision region
    plot_decision_regions(x, y, clf=clf, legend=2)
# Adding axes annotations
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title(str(k))
    plt.show()